package ch.evolutionsoft.rl;

import java.io.Serializable;

import org.nd4j.linalg.api.ndarray.INDArray;

/**
 * An {@link AdversaryTrainingExample} is generated by self play and consists
 * of the board state, action probabilities currentPlayer max or min, the
 * current player value after played until end and iteration for debug analysis.
 * 
 *  Two {@link AdversaryTrainingExample} are considered equals when they have 
 *  the same board state. Existing {@link AdversaryTrainingExample} with a given
 *  board state can get replaced with new action probabilities.
 * 
 * @author evolutionsoft
 */
public class AdversaryTrainingExample implements Serializable {

  INDArray board;
  
  int currentPlayer;
  
  INDArray actionIndexProbabilities;
  
  Float currentPlayerValue;
  
  int iteration;

  public AdversaryTrainingExample(INDArray board, int currentPlayer, 
      INDArray actionIndexProbabilities, int iteration) {
    
    this.board = board.dup();
    this.currentPlayer = currentPlayer;
    this.actionIndexProbabilities = actionIndexProbabilities;
    this.iteration = iteration;
  }

  public Float getCurrentPlayerValue() {
    return currentPlayerValue;
  }

  public void setCurrentPlayerValue(Float currentPlayerValue) {
    this.currentPlayerValue = currentPlayerValue;
  }

  public INDArray getBoard() {
    return board;
  }

  public INDArray getActionIndexProbabilities() {
    return actionIndexProbabilities;
  }

  public int getCurrentPlayer() {
    return currentPlayer;
  }
  
  public boolean equals(Object other) {
    
    if (! (other instanceof AdversaryTrainingExample) ) {
      
      return false;
    }
    
    AdversaryTrainingExample otherExample = (AdversaryTrainingExample) other;
    
    return this.board.equals(otherExample.board);
  }
  
  public int hashCode() {
    
    return this.board.hashCode();
  }
  
  public String toString() {
    
    return "TrainExample {" + 
        this.board.toString() + System.lineSeparator() +
        this.currentPlayer + System.lineSeparator() +
        this.actionIndexProbabilities.toString() + System.lineSeparator() +
        this.currentPlayerValue + System.lineSeparator() +
        "}";
  }
}
